apiVersion: v1
kind: Secret
metadata:
  name: hikvision-creds
  namespace: camaras-ia
type: Opaque
data:
  DB_PASSWORD: dGVzdA==      # 'test' en base64
  CAMERA_USER: YWRtaW4=
  CAMERA_PASS: Y29udHJhc2Vuw6E=