apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camara-ia-storage
  namespace: camaras-ia
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: { requests: { storage: 5Gi } }